--- # Poggit-CI Manifest, Open the CI at https://poggit.pmmp.io/ci/DiscordBot-PMMP/DiscordAccount
build-by-default: true
branches:
- stable
projects:
  DiscordAccount:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.2
...
