name: DiscordAccount
version: 1.0.1-dev
author: JaxkDev
main: JaxkDev\DiscordAccount\Main
src-namespace-prefix: JaxkDev\DiscordAccount
description: A central plugin to create connections between Minecraft and Discord accounts.
website: https://github.com/DiscordBot-PMMP/DiscordAccount

api: 4.0.0

depend:
  - DiscordBot

commands:
  discordlink:
    description: "Link your Minecraft account to your Discord account."
    usage: "/discordlink"
    aliases: [dclink]
    permission: "discordaccount.command.link"
  discordunlink:
    description: "Unlink your Minecraft account from a Discord account."
    usage: "/discordunlink"
    aliases: [ dcunlink ]
    permission: "discordaccount.command.unlink"

permissions:
  discordaccount.command.link:
    default: true
    description: "Allows the user to use the /discordlink command."
  discordaccount.command.unlink:
    default: true
    description: "Allows the user to use the /discordunlink command."